### ISSUE TITLE
Module no longer working

### ISSUE THREAD

**Issue by johnpaulhayes** [Andrewnolan13/DoneDeal#1]
Hiya, 

Looks like this stopped working recently. 
Running ```python tests/cli_mercedes.py``` I'm seeing the folllowing. Maybe DoneDeal change their site? 

```
No matches found, returning 0
retrieved 0 urls matching your criteria
retrieved 0 jsons
converted jsons to DataFrame
Traceback (most recent call last):
  File "/Users/user1/Development/DoneDeal/tests/cli_mercedes.py", line 44, in <module>
    main()
  File "/Users/user1/Development/DoneDeal/tests/cli_mercedes.py", line 20, in main
    df:pd.DataFrame = scraper.DataFrame.copy()[dd.constants.RECOMMENDED_COLUMNS] #alot of data gets returned, RECOMMENDED_COLUMNS is an optional subset of columns 
                      ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/user1/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['make', 'model', 'price', 'fuelType', 'trim', 'transmission', 'engine',\n       'enginePower', 'acceleration', 'seats', 'numDoors', 'colour', 'country',\n       'owners', 'roadTax', 'NCTExpiry', 'bodyType', 'year', 'mileage',\n       'currency', 'sellerType', 'county', 'countyTown', 'geoPoint', 'header',\n       'description', 'friendlyUrl'],\n      dtype='object')] are in the [columns]"
```

**Comment by Andrewnolan13** [comment]
Hi John,

Thanks for letting me know. I'll have a look at it today

**Comment by Andrewnolan13** [comment]
Hi John, you were right, the html has changed slightly. I've made some small changes and it works fine again for me. Do you want to retry and let me know how you get on?

**Comment by johnpaulhayes** [comment]
Legend! Thank you!

**Comment by Andrewnolan13** [comment]
No bother. Don't scrape it too much though, or they will block your IP.
